[package]
name = "ordadb-engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
ordadb-catalog = { path = "../ordadb-catalog" }
ordadb-execution = { path = "../ordadb-execution" }
ordadb-index = { path = "../ordadb-index" }
ordadb-optimizer = { path = "../ordadb-optimizer" }
ordadb-plpgsql = { path = "../ordadb-plpgsql" }
ordadb-search = { path = "../ordadb-search" }
ordadb-sql = { path = "../ordadb-sql" }
ordadb-storage = { path = "../ordadb-storage" }
ordadb-transaction = { path = "../ordadb-transaction" }
ordadb-types = { path = "../ordadb-types" }
serde = { workspace = true, features = ["rc"] }
serde_json.workspace = true
sha2.workspace = true

[dev-dependencies]
tempfile.workspace = true
