[package]
name = "ordadb-connectors"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
async-trait.workspace = true
base64.workspace = true
ed25519-dalek.workspace = true
futures-util.workspace = true
ordadb-types = { path = "../ordadb-types" }
ordadb-windows = { path = "../ordadb-windows" }
reqwest.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
tokio-util.workspace = true
uuid.workspace = true
windows-sys.workspace = true
zeroize.workspace = true

[dev-dependencies]
tempfile.workspace = true

[[test]]
name = "connector_host_e2e"
path = "tests/connector_host_e2e.rs"
harness = false
