[package]
name = "ordadb-execution"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
chrono.workspace = true
ordadb-index = { path = "../ordadb-index" }
ordadb-optimizer = { path = "../ordadb-optimizer" }
ordadb-sql = { path = "../ordadb-sql" }
ordadb-types = { path = "../ordadb-types" }
rust_decimal.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true

[dev-dependencies]
ordadb-catalog = { path = "../ordadb-catalog" }
tempfile.workspace = true
windows-sys.workspace = true
