[package]
name = "ordadb-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
axum.workspace = true
axum-server.workspace = true
ordadb-admin = { path = "../ordadb-admin" }
ordadb-engine = { path = "../ordadb-engine" }
ordadb-protocol = { path = "../ordadb-protocol" }
ordadb-types = { path = "../ordadb-types" }
rand.workspace = true
rustls.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
tokio-util.workspace = true
windows-service.workspace = true
windows-sys.workspace = true
zeroize.workspace = true

[dev-dependencies]
reqwest.workspace = true
tempfile.workspace = true
